-- Seed data: SRS master lists (4.1, Appendix A), SLA defaults (8.1) and settings.
-- Safe to run more than once.

insert into public.master_lists (list_name, value, grp, tags, sort_order) values
('visit_objective', 'New Lead Identification', 'Business Development', array[]::text[], 1),
('visit_objective', 'New Customer Introduction', 'Business Development', array[]::text[], 2),
('visit_objective', 'Existing Customer Relationship', 'Business Development', array[]::text[], 3),
('visit_objective', 'Project Intelligence', 'Business Development', array[]::text[], 4),
('visit_objective', 'Project Qualification', 'Business Development', array[]::text[], 5),
('visit_objective', 'Consultant Relationship Development', 'Business Development', array['networking']::text[], 6),
('visit_objective', 'Contractor Relationship Development', 'Business Development', array['networking']::text[], 7),
('visit_objective', 'Networking / Industry Event', 'Business Development', array['networking']::text[], 8),
('visit_objective', 'Unplanned / Courtesy', 'Business Development', array['networking']::text[], 9),
('visit_objective', 'Partner / Supplier Joint', 'Business Development', array['networking', 'internal']::text[], 10),
('visit_objective', 'Principal / Manufacturer', 'Business Development', array['networking', 'internal']::text[], 11),
('visit_objective', 'Competitor / Market Intelligence', 'Business Development', array['networking', 'internal']::text[], 12),
('visit_objective', 'Internal Project Review', 'Business Development', array['networking', 'internal']::text[], 13),
('visit_objective', 'Other Project-Sales', 'Business Development', array['internal']::text[], 14),
('visit_objective', 'Requirement Gathering', 'Survey & Assessment', array[]::text[], 15),
('visit_objective', 'Initial Site Survey', 'Survey & Assessment', array[]::text[], 16),
('visit_objective', 'Detailed Site Survey', 'Survey & Assessment', array[]::text[], 17),
('visit_objective', 'Existing System Assessment', 'Survey & Assessment', array[]::text[], 18),
('visit_objective', 'Concept Development Meeting', 'Design & Concept', array[]::text[], 19),
('visit_objective', 'Lighting Concept Meeting', 'Design & Concept', array[]::text[], 20),
('visit_objective', 'Technical Design Meeting', 'Design & Concept', array[]::text[], 21),
('visit_objective', 'Lighting Calculation Discussion', 'Design & Concept', array[]::text[], 22),
('visit_objective', 'Control System Design Meeting', 'Design & Concept', array[]::text[], 23),
('visit_objective', 'System Integration Meeting', 'Design & Concept', array[]::text[], 24),
('visit_objective', 'Value Engineering Meeting', 'Design & Concept', array[]::text[], 25),
('visit_objective', 'Alternative Solution Proposal', 'Design & Concept', array[]::text[], 26),
('visit_objective', 'Product Presentation', 'Presentation & Samples', array[]::text[], 27),
('visit_objective', 'Corporate / Capability Presentation', 'Presentation & Samples', array[]::text[], 28),
('visit_objective', 'Product Demonstration', 'Presentation & Samples', array[]::text[], 29),
('visit_objective', 'Sample Submission', 'Presentation & Samples', array[]::text[], 30),
('visit_objective', 'Sample Evaluation', 'Presentation & Samples', array[]::text[], 31),
('visit_objective', 'Mock-up Planning', 'Presentation & Samples', array[]::text[], 32),
('visit_objective', 'Mock-up Demonstration', 'Presentation & Samples', array[]::text[], 33),
('visit_objective', 'Mock-up Approval', 'Presentation & Samples', array[]::text[], 34),
('visit_objective', 'Specification Development', 'Specification & Approval', array[]::text[], 35),
('visit_objective', 'Specification Inclusion', 'Specification & Approval', array['probability_prompt']::text[], 36),
('visit_objective', 'Specification Protection', 'Specification & Approval', array[]::text[], 37),
('visit_objective', 'Brand Approval', 'Specification & Approval', array['probability_prompt']::text[], 38),
('visit_objective', 'Product Approval', 'Specification & Approval', array['probability_prompt']::text[], 39),
('visit_objective', 'Technical Submittal Discussion', 'Specification & Approval', array[]::text[], 40),
('visit_objective', 'Compliance / Standards Meeting', 'Specification & Approval', array[]::text[], 41),
('visit_objective', 'Tender Intelligence', 'Tender & Estimation', array[]::text[], 42),
('visit_objective', 'Pre-Tender Meeting', 'Tender & Estimation', array[]::text[], 43),
('visit_objective', 'Pre-Bid Meeting', 'Tender & Estimation', array[]::text[], 44),
('visit_objective', 'Tender Site', 'Tender & Estimation', array[]::text[], 45),
('visit_objective', 'Tender Clarification Meeting', 'Tender & Estimation', array[]::text[], 46),
('visit_objective', 'BOQ Discussion', 'Tender & Estimation', array[]::text[], 47),
('visit_objective', 'Cost Estimate / Budget Discussion', 'Tender & Estimation', array[]::text[], 48),
('visit_objective', 'Budgetary Proposal Discussion', 'Tender & Estimation', array[]::text[], 49),
('visit_objective', 'Bid Submission', 'Tender & Estimation', array[]::text[], 50),
('visit_objective', 'Tender Opening / Bid Opening', 'Tender & Estimation', array[]::text[], 51),
('visit_objective', 'Quotation Submission', 'Proposal & Negotiation', array[]::text[], 52),
('visit_objective', 'Technical Proposal Presentation', 'Proposal & Negotiation', array[]::text[], 53),
('visit_objective', 'Commercial Proposal Presentation', 'Proposal & Negotiation', array[]::text[], 54),
('visit_objective', 'Proposal Follow-up', 'Proposal & Negotiation', array[]::text[], 55),
('visit_objective', 'Competitor Comparison Meeting', 'Proposal & Negotiation', array['probability_prompt']::text[], 56),
('visit_objective', 'Tender Negotiation', 'Proposal & Negotiation', array[]::text[], 57),
('visit_objective', 'Price Negotiation', 'Proposal & Negotiation', array['probability_prompt']::text[], 58),
('visit_objective', 'Commercial Terms Negotiation', 'Proposal & Negotiation', array[]::text[], 59),
('visit_objective', 'Technical Negotiation', 'Proposal & Negotiation', array[]::text[], 60),
('visit_objective', 'Final Negotiation', 'Proposal & Negotiation', array['probability_prompt']::text[], 61),
('visit_objective', 'Decision-Maker Meeting', 'Proposal & Negotiation', array[]::text[], 62),
('visit_objective', 'Procurement Meeting', 'Proposal & Negotiation', array[]::text[], 63),
('visit_objective', 'Management-Level Meeting', 'Proposal & Negotiation', array[]::text[], 64),
('visit_objective', 'Order Closing', 'Order & Contract', array[]::text[], 65),
('visit_objective', 'Purchase Order Follow-up', 'Order & Contract', array[]::text[], 66),
('visit_objective', 'LOA / Contract Follow-up', 'Order & Contract', array[]::text[], 67),
('visit_objective', 'Contract Clarification Meeting', 'Order & Contract', array[]::text[], 68),
('visit_objective', 'Kick-Off Meeting', 'Execution & Handover', array[]::text[], 69),
('visit_objective', 'Project Coordination Meeting', 'Execution & Handover', array[]::text[], 70),
('visit_objective', 'Design Coordination Meeting', 'Execution & Handover', array[]::text[], 71),
('visit_objective', 'Shop Drawing Meeting', 'Execution & Handover', array[]::text[], 72),
('visit_objective', 'Material Submittal Meeting', 'Execution & Handover', array[]::text[], 73),
('visit_objective', 'Procurement Coordination', 'Execution & Handover', array[]::text[], 74),
('visit_objective', 'Delivery Coordination', 'Execution & Handover', array[]::text[], 75),
('visit_objective', 'Site Readiness Inspection', 'Execution & Handover', array[]::text[], 76),
('visit_objective', 'Installation Coordination', 'Execution & Handover', array[]::text[], 77),
('visit_objective', 'Installation Inspection', 'Execution & Handover', array[]::text[], 78),
('visit_objective', 'Progress Review Meeting', 'Execution & Handover', array[]::text[], 79),
('visit_objective', 'Site Problem-Solving', 'Execution & Handover', array[]::text[], 80),
('visit_objective', 'Variation / Additional Work Discussion', 'Execution & Handover', array[]::text[], 81),
('visit_objective', 'Change Order Discussion', 'Execution & Handover', array[]::text[], 82),
('visit_objective', 'Testing', 'Execution & Handover', array[]::text[], 83),
('visit_objective', 'Commissioning', 'Execution & Handover', array[]::text[], 84),
('visit_objective', 'Lux Measurement / Performance Verification', 'Execution & Handover', array[]::text[], 85),
('visit_objective', 'Consultant Inspection', 'Execution & Handover', array[]::text[], 86),
('visit_objective', 'Client Inspection', 'Execution & Handover', array[]::text[], 87),
('visit_objective', 'Snagging', 'Execution & Handover', array[]::text[], 88),
('visit_objective', 'Snag Rectification Follow-up', 'Execution & Handover', array[]::text[], 89),
('visit_objective', 'Final Acceptance', 'Execution & Handover', array[]::text[], 90),
('visit_objective', 'Handover Meeting', 'Execution & Handover', array[]::text[], 91),
('visit_objective', 'Training', 'Execution & Handover', array[]::text[], 92),
('visit_objective', 'Warranty Discussion', 'After-Sales & Finance', array[]::text[], 93),
('visit_objective', 'Complaint Investigation', 'After-Sales & Finance', array[]::text[], 94),
('visit_objective', 'Service / Maintenance', 'After-Sales & Finance', array[]::text[], 95),
('visit_objective', 'Replacement / Retrofit Opportunity', 'After-Sales & Finance', array[]::text[], 96),
('visit_objective', 'AMC / Service Contract Discussion', 'After-Sales & Finance', array[]::text[], 97),
('visit_objective', 'Invoice Certification Follow-up', 'After-Sales & Finance', array[]::text[], 98),
('visit_objective', 'Payment Collection', 'After-Sales & Finance', array[]::text[], 99),
('visit_objective', 'Retention Collection', 'After-Sales & Finance', array[]::text[], 100),
('visit_objective', 'Bank Guarantee / Documentation Follow-up', 'After-Sales & Finance', array[]::text[], 101),
('visit_objective', 'Project Completion Review', 'After-Sales & Finance', array[]::text[], 102),
('visit_objective', 'Customer Satisfaction', 'After-Sales & Finance', array[]::text[], 103),
('visit_objective', 'Reference / Testimonial', 'After-Sales & Finance', array[]::text[], 104),
('visit_objective', 'Repeat Business Development', 'After-Sales & Finance', array[]::text[], 105),
('visit_objective', 'Cross-Selling', 'After-Sales & Finance', array[]::text[], 106),
('visit_category', 'End-Client', null, '{}'::text[], 1),
('visit_category', 'Architect', null, '{}'::text[], 2),
('visit_category', 'Electrical Consultant', null, '{}'::text[], 3),
('visit_category', 'MEP Consultant', null, '{}'::text[], 4),
('visit_category', 'Interior Designer', null, '{}'::text[], 5),
('visit_category', 'Quantity Surveyor', null, '{}'::text[], 6),
('visit_category', 'Main Contractor', null, '{}'::text[], 7),
('visit_category', 'MEP Contractor', null, '{}'::text[], 8),
('visit_category', 'Specialist Contractor', null, '{}'::text[], 9),
('visit_category', 'Government / Authority', null, '{}'::text[], 10),
('visit_category', 'Developer', null, '{}'::text[], 11),
('visit_outcome', 'Positive', null, '{}'::text[], 1),
('visit_outcome', 'Neutral', null, '{}'::text[], 2),
('visit_outcome', 'Negative', null, '{}'::text[], 3),
('visit_outcome', 'Follow-up Required', null, '{}'::text[], 4),
('visit_outcome', 'Inquiry Received', null, '{}'::text[], 5),
('visit_outcome', 'Lost', null, '{}'::text[], 6),
('project_stage', 'Concept', null, '{}'::text[], 1),
('project_stage', 'Design', null, '{}'::text[], 2),
('project_stage', 'Tender', null, '{}'::text[], 3),
('project_stage', 'Award', null, '{}'::text[], 4),
('project_stage', 'Execution', null, '{}'::text[], 5),
('project_stage', 'Handover', null, '{}'::text[], 6),
('project_stage', 'Operation', null, '{}'::text[], 7),
('missed_reason', 'Customer cancelled', null, '{}'::text[], 1),
('missed_reason', 'Rescheduled by customer', null, '{}'::text[], 2),
('missed_reason', 'Internal priority', null, '{}'::text[], 3),
('missed_reason', 'Travel', null, '{}'::text[], 4),
('missed_reason', 'Other', null, '{}'::text[], 5),
('lost_reason', 'Price', null, '{}'::text[], 1),
('lost_reason', 'Brand not approved', null, '{}'::text[], 2),
('lost_reason', 'Technical', null, '{}'::text[], 3),
('lost_reason', 'Timeline', null, '{}'::text[], 4),
('lost_reason', 'Relationship', null, '{}'::text[], 5),
('lost_reason', 'Project cancelled', null, '{}'::text[], 6),
('lost_reason', 'Other', null, '{}'::text[], 7),
('tender_activity', 'Tender Site', null, '{}'::text[], 1),
('tender_activity', 'Pre-Tender / Pre-Bid Meeting', null, '{}'::text[], 2),
('tender_activity', 'Tender Clarification Meeting', null, '{}'::text[], 3),
('tender_activity', 'Bid Submission', null, '{}'::text[], 4),
('tender_activity', 'Tender Opening / Bid Opening', null, '{}'::text[], 5),
('sample_purpose', 'Evaluation', null, '{}'::text[], 1),
('sample_purpose', 'Client / consultant approval', null, '{}'::text[], 2),
('sample_purpose', 'Mock-up', null, '{}'::text[], 3),
('sample_purpose', 'Demonstration', null, '{}'::text[], 4),
('sample_purpose', 'Other', null, '{}'::text[], 5),
('hold_reason', 'Waiting for client drawings', null, '{}'::text[], 1),
('hold_reason', 'Waiting for client information', null, '{}'::text[], 2),
('hold_reason', 'Waiting for supplier price', null, '{}'::text[], 3),
('hold_reason', 'Client on hold', null, '{}'::text[], 4),
('hold_reason', 'Other', null, '{}'::text[], 5),
('delay_reason', 'Workload', null, '{}'::text[], 1),
('delay_reason', 'Waiting for information', null, '{}'::text[], 2),
('delay_reason', 'Scope change', null, '{}'::text[], 3),
('delay_reason', 'Supplier delay', null, '{}'::text[], 4),
('delay_reason', 'Technical complexity', null, '{}'::text[], 5),
('delay_reason', 'Other', null, '{}'::text[], 6),
('debt_dispute_reason', 'Quantity dispute', null, '{}'::text[], 1),
('debt_dispute_reason', 'Price dispute', null, '{}'::text[], 2),
('debt_dispute_reason', 'Quality issue', null, '{}'::text[], 3),
('debt_dispute_reason', 'Documentation', null, '{}'::text[], 4),
('debt_dispute_reason', 'Other', null, '{}'::text[], 5)
on conflict (list_name, value) do update set grp = excluded.grp, tags = excluded.tags, sort_order = excluded.sort_order;

-- SLA defaults in working minutes (1 working day = 540 minutes, 08:30–17:30)
insert into public.sla_rules (stage, label, target_minutes) values
  ('acceptance', 'Inquiry acceptance', 240),
  ('assignment', 'Assignment with due date', 240),
  ('ack', 'Assignee acknowledgement', 240),
  ('design_small', 'Design – small job', 1620),
  ('design_medium', 'Design – medium job', 2700),
  ('design_large', 'Design – large job / tender', 5400),
  ('design_electrical', 'Electrical-only design', 2700),
  ('design_review', 'Design review by manager', 540),
  ('estimation_small', 'Estimation – small (under LKR 5 M)', 1080),
  ('estimation_medium', 'Estimation – medium (LKR 5–25 M)', 2160),
  ('estimation_large', 'Estimation – large (over LKR 25 M)', 3780),
  ('quotation_approval', 'Quotation approval', 540),
  ('sales_submission', 'Sales submission to client', 540),
  ('approval', 'Approval decision', 540)
on conflict (stage) do nothing;

insert into public.settings (key, value, description) values
  ('timezone', '"Asia/Colombo"', 'Time zone for all clocks and reminders'),
  ('working_hours', '{"start":"08:30","end":"17:30","days":[1,2,3,4,5]}', 'Working hours for SLA clocks (Mon–Fri)'),
  ('plan_deadline', '"13:00"', 'Saturday deadline for next week''s visit plan'),
  ('gps_radius_m', '500', 'Check-in within this distance of the planned location counts as GPS-verified'),
  ('repeat_visit_days', '7', 'Repeat visit to the same organization within N days with the same objective is flagged'),
  ('dormant_days', '60', 'Days without activity before a project is flagged dormant'),
  ('term_short_max_months', '6', 'Short-term projects: up to N months'),
  ('term_medium_max_months', '18', 'Medium-term projects: up to N months'),
  ('gm_approval_value_lkr', '50000000', 'Quotations above this value (LKR equivalent) need GM / DGM approval – TO CONFIRM'),
  ('gm_approval_margin_floor_pct', '15', 'Quotations below this margin % need GM / DGM approval – TO CONFIRM'),
  ('quotation_validity_days', '30', 'Default quotation validity'),
  ('non_moving_days', '14', 'Debt with no status update and no reduction for N days is non-moving'),
  ('sample_sm_overdue_days', '7', 'Alert SM Projects when a returnable sample is N days overdue')
on conflict (key) do nothing;
