import { Platform } from 'react-native';
import { projectNo, type ExecProject, type ExecReport, type PlanItem } from './execution';
import { fmtDateNum, fmtDateTimeY } from './format';
import { deliver } from './hseFill';
import { SiteDoc, TONES, type Cell } from './pdfDoc';
import { ROLE_LABELS } from './roles';
import { supabase } from './supabase';
import type { Attachment, Profile } from './types';

// Daily progress report as a DIMO site document (logo header like the HSE forms): planned activities with the result
// recorded in the report, the narrative, the supervisors' reports of the day, safety, photos per activity and sign-off.

export type ItemUpdate = {
  id: string;
  day: string;
  kind: string;
  title: string;
  zone: string | null;
  qty: number | null;
  unit: string | null;
  supervisor_id: string | null;
  status: PlanItem['status'];
  done_qty: number | null;
  note: string | null;
  photos: string[];
};
export type DailyReport = ExecReport & { item_updates?: ItemUpdate[] };

const RESULT: Record<PlanItem['status'], { t: string; c: (typeof TONES)[keyof typeof TONES] }> = {
  done: { t: 'Done', c: TONES.green },
  partial: { t: 'Partly done', c: TONES.amber },
  not_done: { t: 'Not done', c: TONES.red },
  planned: { t: 'Not updated', c: TONES.grey },
};
const qty = (n: number | null, u: string | null) => (n == null ? '' : `${n}${u ? ` ${u}` : ''}`);

/** Photo bytes for the PDF; on the web large or unusual photos are redrawn as a 1600 px JPEG first */
async function photoBytes(a: Attachment): Promise<{ bytes: Uint8Array | null; type: string }> {
  try {
    const { data } = await supabase.storage.from('files').createSignedUrl(a.storage_path, 600);
    if (!data?.signedUrl) return { bytes: null, type: '' };
    const res = await fetch(data.signedUrl);
    const blob = await res.blob();
    const type = (a.mime_type ?? blob.type ?? '').toLowerCase();
    if (Platform.OS === 'web' && typeof createImageBitmap === 'function' && (blob.size > 900_000 || !/jpe?g|png/.test(type))) {
      const bmp = await createImageBitmap(blob);
      const s = Math.min(1, 1600 / Math.max(bmp.width, bmp.height));
      const c = document.createElement('canvas');
      c.width = Math.round(bmp.width * s);
      c.height = Math.round(bmp.height * s);
      c.getContext('2d')?.drawImage(bmp, 0, 0, c.width, c.height);
      const jpg = await new Promise<Blob | null>((ok) => c.toBlob(ok, 'image/jpeg', 0.82));
      if (jpg) return { bytes: new Uint8Array(await jpg.arrayBuffer()), type: 'image/jpeg' };
    }
    return { bytes: new Uint8Array(await blob.arrayBuffer()), type };
  } catch {
    return { bytes: null, type: '' };
  }
}

export async function printDailyReport(r: DailyReport, project: ExecProject, people: Record<string, Profile>, generatedBy: string) {
  const name = (id: string | null) => (id ? people[id]?.full_name ?? '' : '');
  const role = (id: string | null) => {
    const x = id ? people[id]?.role : null;
    return x ? ROLE_LABELS[x] ?? '' : '';
  };
  const ae = r.level === 'ae';
  const [atts, sups, planItems] = await Promise.all([
    supabase.from('attachments').select('*').eq('entity_type', 'exec_report').eq('entity_id', r.id).is('archived_at', null).order('uploaded_at'),
    ae ? supabase.from('exec_reports').select('*').eq('exec_project_id', r.exec_project_id).eq('report_date', r.report_date).eq('level', 'supervisor').order('submitted_at') : Promise.resolve({ data: [] }),
    r.item_updates?.length ? Promise.resolve({ data: [] }) : supabase.from('exec_plan_items').select('*').eq('exec_project_id', r.exec_project_id).eq('day', r.report_date).order('created_at'),
  ]);
  const files = (atts.data ?? []) as Attachment[];
  const items: ItemUpdate[] = r.item_updates?.length
    ? r.item_updates
    : ((planItems.data ?? []) as PlanItem[])
        .filter((i) => ae || i.supervisor_id === r.author_id)
        .map((i) => ({ id: i.id, day: i.day, kind: i.kind, title: i.title, zone: i.zone, qty: i.qty, unit: i.unit, supervisor_id: i.supervisor_id, status: i.status, done_qty: i.done_qty, note: i.result_note, photos: [] }));
  const no = projectNo(project);
  const d = await SiteDoc.create(
    {
      system: 'DIMO PLC – LIGHTING PROJECTS · SITE EXECUTION',
      title: 'DAILY PROGRESS REPORT',
      subtitle: ae ? 'Assistant Engineer report' : 'Subcontractor supervisor report',
      boxes: [
        ['Report No', `${no || 'EXP'}/DR/${r.report_date.replace(/-/g, '')}${ae ? '' : '-S'}`],
        ['Date', fmtDateNum(r.report_date)],
      ],
    },
    `Generated by ${generatedBy} on ${fmtDateTimeY(new Date().toISOString())} · DIMO Lighting Ops · Confidential`,
  );

  d.keyValues([
    ['Project', [no, project.name].filter(Boolean).join(' – ')],
    ['Client', project.client_name ?? ''],
    ['Site', project.site_address ?? ''],
    ['Report date', fmtDateNum(r.report_date)],
    ['Prepared by', [name(r.author_id), role(r.author_id)].filter(Boolean).join(' – ')],
    ['Submitted', `${fmtDateTimeY(r.submitted_at)}${r.is_late ? ' (late)' : ''}`],
    ['Status', r.status === 'verified' ? `${ae ? 'Reviewed' : 'Verified'} by ${name(r.reviewed_by)}` : r.status === 'returned' ? 'Returned for correction' : 'Waiting for review'],
    ['Weather', r.weather ?? ''],
    ...(!ae ? ([['Crew on site', `${r.crew_count ?? 0}${r.crew ? ` · ${r.crew}` : ''}`]] as [string, string][]) : []),
    ...(r.visitors ? ([['Visitors', r.visitors]] as [string, string][]) : []),
  ]);

  d.section('A. Planned activities – progress');
  if (items.length) {
    d.table(
      ['#', 'Activity', 'Supervisor', 'Planned', 'Done', 'Result', 'Details / reason'],
      [0.04, 0.3, 0.14, 0.09, 0.09, 0.1, 0.24],
      items.map((it, i): Cell[] => [
        { text: String(i + 1), align: 'center' },
        `${it.title}${it.zone ? ` – ${it.zone}` : ''}${it.day !== r.report_date ? ` (planned ${fmtDateNum(it.day)})` : ''}${it.photos?.length ? ` · ${it.photos.length} photo${it.photos.length > 1 ? 's' : ''}` : ''}`,
        name(it.supervisor_id),
        { text: qty(it.qty, it.unit), align: 'center' },
        { text: qty(it.done_qty, it.unit), align: 'center' },
        { text: RESULT[it.status].t, bold: true, color: RESULT[it.status].c },
        it.note ?? '',
      ]),
    );
  } else d.para('Planned activities', 'No planned activities for this day.');

  d.section('B. Work on site');
  d.para('Work done', r.work_done);
  if (r.inspections) d.para('Inspections and tests', r.inspections);
  if (r.delays) d.para('Delays and reasons', r.delays);
  if (r.issues) d.para('Issues / needs (materials, access, drawings)', r.issues);
  if (r.work_next) d.para('Planned for tomorrow', r.work_next);

  const supReps = (sups.data ?? []) as ExecReport[];
  if (ae) {
    d.section('C. Subcontractor supervisor reports');
    if (supReps.length)
      d.table(
        ['Supervisor', 'Crew', 'Status', 'Work done'],
        [0.22, 0.1, 0.14, 0.54],
        supReps.map((s) => [name(s.author_id), { text: String(s.crew_count ?? 0), align: 'center' }, { text: s.status === 'verified' ? 'Verified' : s.status === 'returned' ? 'Returned' : 'To verify', color: s.status === 'verified' ? TONES.green : TONES.amber }, s.work_done]),
      );
    else d.para('Supervisor reports', 'No supervisor reports for this day.');
  }

  d.section(`${ae ? 'D' : 'C'}. Health and safety`);
  d.keyValues(
    [
      ['Toolbox talk', r.toolbox_talk ? `Held – ${r.toolbox_topic ?? ''}` : 'Not held'],
      ['Daily safety check', r.safety_check ? 'Done' : 'Not done'],
      ['HSE notes', r.hse_notes ?? ''],
    ],
    1,
  );

  const images = files.filter((a) => (a.mime_type ?? '').startsWith('image/') || /\.(jpe?g|png|webp|heic)$/i.test(a.file_name));
  const docs = files.filter((a) => !images.includes(a));
  const itemOf = new Map<string, ItemUpdate>();
  for (const it of items) for (const p of it.photos ?? []) itemOf.set(p, it);
  const ordered = [...images.filter((a) => itemOf.has(a.id)), ...images.filter((a) => !itemOf.has(a.id))];
  if (ordered.length) {
    d.section(`${ae ? 'E' : 'D'}. Photos`);
    const loaded = await Promise.all(ordered.map(photoBytes));
    await d.photos(
      ordered.map((a, i) => {
        const it = itemOf.get(a.id);
        return { ...loaded[i], caption: `${i + 1}. ${it ? `${it.title}${it.zone ? ` – ${it.zone}` : ''} (${RESULT[it.status].t})` : 'General site photo'} · ${fmtDateTimeY(a.uploaded_at)}` };
      }),
    );
  }
  if (docs.length) {
    d.section('Documents attached in the app');
    d.table(['#', 'File', 'Uploaded'], [0.06, 0.64, 0.3], docs.map((a, i) => [{ text: String(i + 1), align: 'center' }, a.file_name, fmtDateTimeY(a.uploaded_at)]));
  }

  d.section('Sign-off');
  d.signOff([
    [ae ? 'Prepared by (Assistant Engineer)' : 'Prepared by (Supervisor)', name(r.author_id), r.submitted_at],
    [ae ? 'Reviewed by (Senior Electrical Engineer)' : 'Verified by (Assistant Engineer)', r.status === 'verified' ? name(r.reviewed_by) : '', r.status === 'verified' ? r.reviewed_at : null],
  ]);
  if (r.review_note) d.para('Review comment', r.review_note);

  await deliver(await d.save(), `Daily report ${no} ${r.report_date} ${name(r.author_id)}`, 'daily_report', `${project.name} ${r.report_date}`);
}
