import { File as FsFile, Paths } from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import writeXlsxFile from 'write-excel-file/universal';
import { supabase } from './supabase';

// Branded report export (Section 9.5): DIMO logo, title, filters, report information block,
// repeated table headers, bold totals, page X of Y, "Confidential" footer and a watermark
// with the generating user and time. Every run is logged (Section 9.7).

export type Column<T> = { header: string; value: (row: T) => string | number | null | undefined; align?: 'right'; width?: number };

export type ReportMeta = {
  key: string;
  title: string;
  filters: string;           // e.g. "Long term projects – Hospitality – Win probability ≥ 50%"
  period?: string;
  currencyNote?: string;     // e.g. "USD and LKR shown separately; consolidated at 1 USD = 300 LKR"
  generatedBy: string;       // "Name – Role"
  landscape?: boolean;
  logoUrl?: string | null;   // maintained by the System Administrator (settings.report_logo_url)
};

export const esc = (v: unknown) =>
  String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string);

export type Section<T> = { heading?: string; rows: T[]; totals?: Partial<Record<string, string | number>>; colour?: string };

export function reportHtml<T>(meta: ReportMeta, columns: Column<T>[], sections: Section<T>[], extraHtml = '') {
  const now = new Date().toLocaleString('en-GB', { timeZone: 'Asia/Colombo' });
  const wide = meta.landscape ?? columns.length > 7;
  const logo = meta.logoUrl
    ? `<img src="${esc(meta.logoUrl)}" style="height:36px;width:auto;object-fit:contain" />`
    : `<div style="font:800 26px/1 Arial;color:#C8102E;letter-spacing:1px">DIMO</div>`;
  const table = (s: Section<T>) => `
    ${s.heading ? `<h2 style="background:${s.colour ?? '#F2F2F2'};color:${s.colour ? '#fff' : '#111'}">${esc(s.heading)}</h2>` : ''}
    <table>
      <thead><tr>${columns.map((c) => `<th style="text-align:${c.align ?? 'left'}">${esc(c.header)}</th>`).join('')}</tr></thead>
      <tbody>
        ${s.rows.map((r) => `<tr>${columns.map((c) => `<td style="text-align:${c.align ?? 'left'}">${esc(c.value(r))}</td>`).join('')}</tr>`).join('')}
        ${s.totals ? `<tr class="total">${columns.map((c) => `<td style="text-align:${c.align ?? 'left'}">${esc(s.totals?.[c.header] ?? '')}</td>`).join('')}</tr>` : ''}
      </tbody>
    </table>`;
  return `<!doctype html><html><head><meta charset="utf-8" />
<style>
  @page { size: A4 ${wide ? 'landscape' : 'portrait'}; margin: 18mm 12mm 16mm 12mm;
    @bottom-left { content: "Confidential – for internal use · DIMO Lighting Operations System"; font: 8px Arial; color: #666; }
    @bottom-right { content: "Page " counter(page) " of " counter(pages); font: 8px Arial; color: #666; } }
  body { font: 10px Arial, Helvetica, sans-serif; color: #111; }
  header { display: flex; align-items: center; gap: 16px; border-bottom: 2px solid #C8102E; padding-bottom: 8px; margin-bottom: 10px; }
  h1 { font-size: 16px; margin: 0; } .sub { color: #555; margin-top: 2px; }
  .info { display: grid; grid-template-columns: 1fr 1fr; gap: 2px 16px; background: #F7F7F7; padding: 8px; margin-bottom: 12px; }
  h2 { font-size: 11px; padding: 4px 6px; margin: 14px 0 4px; }
  table { width: 100%; border-collapse: collapse; page-break-inside: auto; }
  thead { display: table-header-group; } tr { page-break-inside: avoid; }
  th { background: #222; color: #fff; padding: 4px; font-size: 9px; } td { padding: 3px 4px; border-bottom: 1px solid #E3E3E3; }
  tr.total td { font-weight: bold; border-top: 1.5px solid #111; }
  .wm { position: fixed; top: 45%; left: 5%; width: 90%; text-align: center; transform: rotate(-30deg);
        font: bold 34px Arial; color: rgba(200,16,46,0.07); z-index: 0; pointer-events: none; }
  .foot { position: fixed; bottom: -10mm; left: 0; right: 0; font-size: 8px; color: #666; }
</style></head><body>
<div class="wm">${esc(meta.generatedBy)} · ${esc(now)}</div>
<header>${logo}<div><h1>${esc(meta.title)}</h1><div class="sub">Lighting Solutions · ${esc(meta.filters || 'All records in your scope')}</div></div></header>
<div class="info">
  <div><b>Generated by:</b> ${esc(meta.generatedBy)}</div><div><b>Date and time:</b> ${esc(now)}</div>
  <div><b>Reporting period:</b> ${esc(meta.period ?? '—')}</div><div><b>Currency basis:</b> ${esc(meta.currencyNote ?? 'Original currency shown on every value')}</div>
</div>
${extraHtml}
${sections.map(table).join('')}
<div class="foot">Generated by ${esc(meta.generatedBy)} on ${esc(now)} · Confidential – for internal use</div>
</body></html>`;
}

async function logRun(key: string, filters: string, format: 'pdf' | 'xlsx' | 'preview') {
  const { data } = await supabase.auth.getUser();
  if (data.user) await supabase.from('report_runs').insert({ user_id: data.user.id, report_key: key, filters: { text: filters }, format });
}

export async function exportPdf<T>(meta: ReportMeta, columns: Column<T>[], sections: Section<T>[], extraHtml = '') {
  const html = reportHtml(meta, columns, sections, extraHtml);
  await printHtml(html, { key: meta.key, filters: meta.filters, title: meta.title, landscape: meta.landscape ?? columns.length > 7 });
}

/** Any ready HTML page as a PDF: the print dialog on the web ("Save as PDF"), a shared PDF file on phones. Logged like reports. */
export async function printHtml(html: string, o: { key: string; filters: string; title: string; landscape?: boolean }) {
  await logRun(o.key, o.filters, 'pdf');
  if (Platform.OS === 'web') {
    // expo-print on the web ignores the html and prints the app screen (one page) – print the document itself instead.
    await printWeb(html);
    return;
  }
  const { uri } = await Print.printToFileAsync({ html, width: o.landscape ? 842 : 595, height: o.landscape ? 595 : 842 });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', UTI: 'com.adobe.pdf', dialogTitle: o.title });
}

/** Web: show the document instead of the app only while printing, then open the print dialog ("Save as PDF").
 * Printing the page itself (not a frame) works the same in every browser, Safari on iPhone included. */
function printWeb(html: string): Promise<void> {
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const css = [...doc.querySelectorAll('style')].map((x) => x.textContent ?? '').join('\n');
  document.getElementById('__print')?.remove();
  document.getElementById('__print_css')?.remove();
  const style = document.createElement('style');
  style.id = '__print_css';
  style.textContent = `@media screen { #__print { display: none !important; } }
@media print {
  html, body { height: auto !important; min-height: 0 !important; overflow: visible !important; position: static !important; background: #fff !important; }
  body > *:not(#__print) { display: none !important; }
  #__print { display: block !important; }
  ${css.replace(/\bbody\b/g, '#__print')}
}`;
  const root = document.createElement('div');
  root.id = '__print';
  root.innerHTML = doc.body.innerHTML;
  document.head.appendChild(style);
  document.body.appendChild(root);
  const cleanup = () => {
    root.remove();
    style.remove();
    window.removeEventListener('afterprint', cleanup);
  };
  window.addEventListener('afterprint', cleanup);
  return new Promise((resolve) => {
    const imgs = [...root.querySelectorAll('img')].filter((im) => !im.complete);
    let started = false;
    const go = () => {
      if (started) return;
      started = true;
      window.print();
      resolve();
    };
    imgs.forEach((im) => im.addEventListener('load', () => imgs.every((x) => x.complete) && go()));
    imgs.forEach((im) => im.addEventListener('error', go));
    setTimeout(go, imgs.length ? 1500 : 50);
  });
}

function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(reader.error);
    reader.onload = () => resolve(String(reader.result).split(',')[1] ?? '');
    reader.readAsDataURL(blob);
  });
}

export async function exportExcel<T>(meta: ReportMeta, columns: Column<T>[], sections: Section<T>[]) {
  const header = columns.map((c) => ({ value: c.header, fontWeight: 'bold' as const }));
  const data: ({ value?: string | number; fontWeight?: 'bold' } | null)[][] = [
    [{ value: meta.title, fontWeight: 'bold' }],
    [{ value: `Lighting Solutions · ${meta.filters}` }],
    [{ value: `Generated by ${meta.generatedBy} · ${new Date().toLocaleString('en-GB', { timeZone: 'Asia/Colombo' })}` }],
    [],
  ];
  for (const s of sections) {
    if (s.heading) data.push([{ value: s.heading, fontWeight: 'bold' }]);
    data.push(header);
    for (const r of s.rows) {
      data.push(columns.map((c) => {
        const v = c.value(r);
        return v == null ? null : { value: v };
      }));
    }
    if (s.totals) data.push(columns.map((c) => ({ value: s.totals?.[c.header] ?? '', fontWeight: 'bold' as const })));
    data.push([]);
  }
  const blob = await writeXlsxFile(data as never, { columns: columns.map((c) => ({ width: c.width ?? 18 })) } as never).toBlob();
  await logRun(meta.key, meta.filters, 'xlsx');
  const name = `${meta.title.replace(/[^A-Za-z0-9]+/g, '_')}_${new Date().toISOString().slice(0, 10)}.xlsx`;
  if (Platform.OS === 'web') {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = name;
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 5000);
    return;
  }
  const file = new FsFile(Paths.cache, name);
  file.create({ overwrite: true });
  file.write(await blobToBase64(blob), { encoding: 'base64' });
  await Sharing.shareAsync(file.uri, {
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    dialogTitle: meta.title,
  });
}
